export const ACTION_TYPES = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  TYPE_NAME: 'TYPE_NAME',
  TYPE_DEPARTMENT: 'TYPE_DEPARTMENT',
  TYPE_PRICE: 'TYPE_PRICE',
  TYPE_SEARCH: 'TYPE_SEARCH',
};